USE PracABD1;

CREATE TABLESPACE `TBLS_clientes` ADD DATAFILE 'DF_clientes.idb' ENGINE=INNODB;

CREATE TABLESPACE `TBLS_juegos` ADD DATAFILE 'DF_juegos.idb' ENGINE=INNODB;

CREATE TABLESPACE `TBLS_clientes_juegos` ADD DATAFILE 'DF_clientes_juegos.idb' ENGINE=INNODB;
