CREATE TABLESPACE TBLS_clientes ADD DATAFILE 'DF_clientes.ibd' ENGINE=INNODB;

CREATE TABLESPACE TBLS_juegos ADD DATAFILE 'DF_juegos.ibd' ENGINE=INNODB;

CREATE TABLESPACE TBLS_clientes_juegos ADD DATAFILE 'DF_clientes_juegos.ibd' ENGINE=INNODB;
