USE PracABD1;

ALTER TABLE clientes_juegos
ADD CONSTRAINT FK_ClienteID FOREIGN KEY (ClienteID) REFERENCES clientes(ClienteID),
ADD CONSTRAINT FK_JuegoID FOREIGN KEY (JuegoID) REFERENCES juegos(JuegoID);